In [2]:
import numpy as np
import pandas as pd

### Task 1
Create a Python list to represent a playlist of 5 song durations in seconds (e.g., [210, 180, 245, 200, 175]). Print the total duration of the playlist.

In [3]:
# Playlist of 5 song durations in seconds
durations = [210, 180, 245, 200, 175]

# Vector representation using NumPy
durations_vector = np.array(durations)

# Calculate total duration
total_duration = np.sum(durations_vector)

print("Song Durations (seconds):", durations_vector)
print("Total Duration (seconds):", total_duration)

Song Durations (seconds): [210 180 245 200 175]
Total Duration (seconds): 1010


### Task 2
Represent a 3x3 matrix in Python to store the ratings (1-5) given by 3 friends to 3 different food items on Swiggy. Print the matrix and display the rating each friend gave to the second food item.

In [4]:
# 3x3 matrix: rows = 3 friends, columns = 3 food items
ratings_matrix = np.array([
    [4, 5, 3],  # Friend 1
    [3, 4, 2],  # Friend 2
    [5, 3, 4]   # Friend 3
])

print("Ratings Matrix (3x3):")
print(ratings_matrix)

# Ratings for the second food item (column index 1)
second_item_ratings = ratings_matrix[:, 1]

print("\nRating each friend gave to the second food item:")
for i, rating in enumerate(second_item_ratings, start=1):
    print(f"Friend {i}: {rating}")

Ratings Matrix (3x3):
[[4 5 3]
 [3 4 2]
 [5 3 4]]

Rating each friend gave to the second food item:
Friend 1: 5
Friend 2: 4
Friend 3: 3


### Task 3
Given a matrix representing the number of orders for 4 different dishes across 3 days (rows: days, columns: dishes), write code to calculate and print the total orders for each dish.

In [5]:
# 3x4 matrix: 3 days (rows) x 4 dishes (columns)
orders_matrix = np.array([
    [15, 22, 10, 8],   # Day 1
    [20, 18, 14, 12],  # Day 2
    [25, 30, 18, 15]   # Day 3
])

# Sum across rows (axis=0) to get total orders per dish
total_orders_per_dish = np.sum(orders_matrix, axis=0)

# Display using pandas DataFrame for clear column representation
dishes = ["Dish 1", "Dish 2", "Dish 3", "Dish 4"]
orders_df = pd.DataFrame(orders_matrix, index=["Day 1", "Day 2", "Day 3"], columns=dishes)

print("Orders Matrix:")
print(orders_df)

print("\nTotal Orders for Each Dish:")
for dish, total in zip(dishes, total_orders_per_dish):
    print(f"{dish}: {total}")

Orders Matrix:
       Dish 1  Dish 2  Dish 3  Dish 4
Day 1      15      22      10       8
Day 2      20      18      14      12
Day 3      25      30      18      15

Total Orders for Each Dish:
Dish 1: 60
Dish 2: 70
Dish 3: 42
Dish 4: 35


### Task 4
Imagine you have a table of 5 Flipkart products with columns for price and quantity sold. Represent this data as a matrix in Python, then write a function to calculate the total revenue for each product.

In [6]:
# 5x2 matrix: [Price, Quantity Sold] for 5 products
flipkart_data = np.array([
    [499, 12],   # Product 1
    [1299, 5],   # Product 2
    [299, 25],   # Product 3
    [899, 8],    # Product 4
    [1999, 3]    # Product 5
])

def calculate_total_revenue(matrix):
    prices = matrix[:, 0]
    quantities = matrix[:, 1]
    revenues = prices * quantities
    return revenues

# Calculate revenues
revenues = calculate_total_revenue(flipkart_data)

# Tabular display
products = [f"Product {i}" for i in range(1, 6)]
df_products = pd.DataFrame({
    "Product": products,
    "Price": flipkart_data[:, 0],
    "Quantity Sold": flipkart_data[:, 1],
    "Total Revenue": revenues
})

print(df_products.to_string(index=False))

  Product  Price  Quantity Sold  Total Revenue
Product 1    499             12           5988
Product 2   1299              5           6495
Product 3    299             25           7475
Product 4    899              8           7192
Product 5   1999              3           5997
